name: run-flake8
on: [push]
jobs:
    Run-flake8:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install poetry
              run: pip install poetry
            - name: Install flake8
              run: pip install flake8
            - name: Run flake8
              run: make lint
