name: run-flake8
on: [push]
jobs:
    Run-flake8:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Run flake8
              run: make lint
